services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lapor-app
    restart: always
    env_file: .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - .:/var/www/html

  web:
    image: nginx:alpine
    container_name: lapor-web
    restart: always
    ports:
      - '8081:80'
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
